cmake $SRCROOT/llvm-project/compiler-rt \
-G Ninja \
-D CMAKE_TOOLCHAIN_FILE=$SRCROOT/cmake/compiler-rt.cmake \
-D CMAKE_SYSROOT=$SYSROOT \
-D CMAKE_INSTALL_PREFIX=/usr/lib/clang/$(llvm-config --version) \
-D LLVM_CONFIG_PATH=/usr/bin/llvm-config

# -D COMPILER_RT_USE_BUILTINS_LIBRARY=ON \
# -D COMPILER_RT_BUILD_BUILTINS=ON \
# -D COMPILER_RT_BUILD_LIBFUZZER=OFF \
# -D COMPILER_RT_BUILD_MEMPROF=OFF \
# -D COMPILER_RT_BUILD_PROFILE=OFF \
# -D COMPILER_RT_BUILD_SANITIZERS=OFF \
# -D COMPILER_RT_BUILD_XRAY=OFF \
# -D COMPILER_RT_DEFAULT_TARGET_ONLY=ON \
# -D COMPILER_RT_INCLUDE_TESTS=OFF \
# -D COMPILER_RT_BUILD_CRT=ON \
# -D COMPILER_RT_BUILD_ORC=OFF \
# -D CMAKE_SIZEOF_VOID_P=4
